export const analytics = {
  trackEvent: jest.fn(),
  trackSudokuGameStart: jest.fn(),
  trackSudokuGameComplete: jest.fn(),
  trackSudokuGameOver: jest.fn(),
  trackSudokuMoveMade: jest.fn(),
  trackSudokuHintUsed: jest.fn(),
  trackSudokuNoteToggle: jest.fn(),
  trackSudokuDifficultyChange: jest.fn(),
  trackSudokuPause: jest.fn(),
  trackSudokuResume: jest.fn(),
  trackSudokuReset: jest.fn(),
  trackPuzzleGameStart: jest.fn(),
  trackPuzzleGameComplete: jest.fn(),
  trackPuzzlePieceDrag: jest.fn(),
  trackPuzzlePiecePlace: jest.fn(),
  trackPuzzleDifficultyChange: jest.fn(),
  trackPuzzlePause: jest.fn(),
  trackPuzzleResume: jest.fn(),
  trackPuzzleReset: jest.fn(),
  trackPuzzleClear: jest.fn(),
  trackPuzzleNewImage: jest.fn(),
  trackScreenView: jest.fn(),
  trackBackClick: jest.fn(),
  trackThemeChanged: jest.fn(),
  trackSoundToggled: jest.fn(),
  trackLeaderboardViewed: jest.fn(),
  trackLeaderboardTabChange: jest.fn(),
  trackApiError: jest.fn(),
  trackImageLoadError: jest.fn(),
  trackGameSaveError: jest.fn(),
  trackAppError: jest.fn(),
  enable: jest.fn(),
  disable: jest.fn(),
  getSessionStats: jest.fn(() => ({ duration: 0, eventsCount: 0 })),
  getEvents: jest.fn(() => []),
  clearEvents: jest.fn(),
};

export const useAnalytics = () => analytics;